name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Setting up"
      - run: echo "Installing"
      - run: echo "Building..."
  
  test1:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Parallel Test 1..."
      
  test2:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Parallel Test 2..."
  
  test:
    needs: [test1, test2]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Main Test..."
  
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."